[build]
builder = "nixpacks"
watchPatterns = [
  "client/**/*.ts",
  "client/**/*.tsx",
  "server/**/*.ts",
  "shared/**/*.ts",
  "Procfile",
  "railway.toml",
  "railway-start.js"
]

[deploy]
startCommand = "web"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[phases.setup]
aptPkgs = ["npm", "nodejs"]

[phases.build]
cmds = [
  "npm install",
  "npm run build"
]

[phases.deploy]
cmd = "node --experimental-modules railway-start.js"